### ISSUE TITLE
[FEATURE] Create Linux & MacOS example projects

### ISSUE THREAD

**Issue by Samuel-de-Oliveira** [The-Young-Programmer/C-CPP-Programming-Project#8]
### Detailed description

I've cloned this repo and I notice that all the programs is created only for Windows.

### Context

So for leaning proposes of everyone the project need examples that's works for all systems.

P. S. I use Linux so maybe a can help about this.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by The-Young-Programmer** [comment]
Okay thanks will work on that.

**Comment by The-Young-Programmer** [comment]
Hi there, thanks for helping me .
Where you able to make it work on Linux ?

**Comment by gabriel-eduardo-dev** [comment]
Hello, we could create a makefile or cmake to make cross-platform projects

**Comment by The-Young-Programmer** [comment]
@Gabriel160204  
Hey! I'm so glad you join.
I think it's a great idea. I've never done it before, but I'm sure I can figure it out.
If you know how to do that, pls go ahead, I will need your help.

**Comment by The-Young-Programmer** [comment]
@Samuel-de-Oliveira @Gabriel160204 
Thank you 😊.
